<a href="https://colab.research.google.com/github/Indian-otaku/Introduction_To_PyTorch/blob/main/Introduction_to_dl_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
torch.__version__

'1.13.1+cu116'

In [ ]:
value = torch.tensor(29)
print(value)
print(value.item())

tensor(29)
29


In [ ]:
MATRIX = torch.tensor([[1,2],
                       [3,6]])
print(MATRIX.ndim)
print(MATRIX.shape)
MATRIX[0][0].item()

2
torch.Size([2, 2])


1

In [ ]:
TENSOR = torch.tensor([[[1,2,3,4],
                        [3,5,1,3],
                        [5,2,3,4]]])
print(TENSOR.shape)
print(TENSOR[0][1][2])

torch.Size([1, 3, 4])
tensor(1)


Random Tensors

In [ ]:
TENSOR = torch.rand(4,3,5)
TENSOR

tensor([[[0.8291, 0.3961, 0.0363, 0.3566, 0.4590],
         [0.2038, 0.0481, 0.8299, 0.8051, 0.0830],
         [0.9071, 0.3983, 0.0380, 0.5156, 0.7668]],

        [[0.7451, 0.3953, 0.0047, 0.5908, 0.2454],
         [0.3039, 0.3690, 0.9831, 0.3846, 0.9350],
         [0.6144, 0.3788, 0.9047, 0.0644, 0.0059]],

        [[0.1205, 0.0874, 0.9243, 0.1775, 0.2361],
         [0.2554, 0.4146, 0.8158, 0.3898, 0.5776],
         [0.8544, 0.5882, 0.2487, 0.7133, 0.9825]],

        [[0.9989, 0.8880, 0.0822, 0.1655, 0.0812],
         [0.6620, 0.9244, 0.3812, 0.0238, 0.2426],
         [0.5702, 0.2795, 0.4411, 0.1154, 0.7564]]])

In [ ]:
TENSOR1 = torch.rand(2,4,3)
TENSOR1

tensor([[[0.8241, 0.8821, 0.8420],
         [0.3019, 0.5073, 0.8362],
         [0.4688, 0.6170, 0.1153],
         [0.9418, 0.3520, 0.2997]],

        [[0.2934, 0.3156, 0.3574],
         [0.8529, 0.1172, 0.5718],
         [0.8760, 0.4186, 0.3349],
         [0.6169, 0.4761, 0.7558]]])

Setting some commmon parameter

In [ ]:
TENSOR_int32 = torch.tensor([[7, 2] ,[4, 5], [3,1]], 
                      dtype=torch.int32,
                      device=None,
                      requires_grad=False)
TENSOR_int32.shape

torch.Size([3, 2])

In [ ]:
TENSOR_int16 = torch.tensor([[1,3,4,2]], dtype=torch.int32)
TENSOR_int16.shape

torch.Size([1, 4])

In [ ]:
ten1 = torch.randn(2,3,4)
ten2 = torch.randn(2,4,3)


In [ ]:
print(ten1,"Shape: ",ten1.shape)
print(ten2,"Shape: ",ten2.shape)

tensor([[[ 1.2477,  0.2904,  1.9808, -0.5265],
         [ 0.1773, -0.2786,  1.0817,  0.0996],
         [-1.6852, -0.5641, -0.2886, -1.4774]],

        [[-0.5559,  0.3187, -0.5711, -0.1991],
         [ 0.3697,  0.7482,  0.6560, -1.0723],
         [-0.0229, -1.7132, -0.7945,  1.0120]]]) Shape:  torch.Size([2, 3, 4])
tensor([[[ 1.4915, -0.5411,  0.1831],
         [-2.1096,  1.0750, -0.9567],
         [ 0.2276,  0.7969, -0.2210],
         [-0.2855,  0.5075,  0.2039]],

        [[-1.8019, -1.4734, -0.0839],
         [ 0.3692, -0.0584,  1.7011],
         [ 1.1546,  1.8182, -0.9418],
         [ 0.0106,  0.1784,  0.4842]]]) Shape:  torch.Size([2, 4, 3])


In [ ]:
list(torch.matmul(ten1, ten2))

[tensor([[ 1.8495,  0.9484, -0.5944],
         [ 1.0700,  0.5171,  0.0803],
         [-0.9674, -0.6743, -0.0063]]), tensor([[ 0.4579, -0.2733,  1.0302],
         [ 0.3561,  0.4130,  0.1046],
         [-1.4979, -1.1303, -1.6741]])]

Tensor aggregation values - min, max, mean, sum etc..

In [ ]:
tensor = torch.arange(0,100,10)
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
tensor = tensor.type(torch.float16)
tensor.mean()

tensor(45., dtype=torch.float16)

In [ ]:
tensor[tensor.argmin()]

tensor(0., dtype=torch.float16)

In [ ]:
tensor_stacked = torch.stack([ tensor, tensor, tensor], dim=0)

In [ ]:
# Both methods of indexing works!!
tensor_stacked[1][4] = 692   
tensor_stacked[1,5] = 22
tensor_stacked

tensor([[  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.],
        [  0.,  10.,  20.,  30., 692.,  22.,  60.,  70.,  80.,  90.],
        [  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90.]],
       dtype=torch.float16)

In [ ]:
tensor_stacked.shape

torch.Size([3, 10])

In [ ]:
x = torch.randn(2,4,3)
x.shape

torch.Size([2, 4, 3])

In [ ]:
x_reshaped = x.permute(1,0,2)
x_reshaped.shape

torch.Size([4, 2, 3])

In [ ]:
x = torch.randn(1,2,1,6,1,3)
x.shape

torch.Size([1, 2, 1, 6, 1, 3])

In [ ]:
x_squeezed = x.squeeze()
x_squeezed.shape

torch.Size([2, 6, 3])

In [ ]:
x_unsqueezed = x_squeezed.unsqueeze(2)
x_unsqueezed.shape

torch.Size([2, 6, 1, 3])

In [ ]:
x.numpy()

array([[[[[[ 0.2551876 , -0.253135  ,  0.44701   ]],

          [[ 0.37118053, -0.41854778,  0.22729127]],

          [[ 2.3916469 , -0.04884563, -0.3171588 ]],

          [[ 2.0215845 , -0.12431845,  0.46505424]],

          [[ 1.0046515 , -0.04057334, -0.81888187]],

          [[ 0.57072514,  0.9665199 , -0.0668356 ]]]],



        [[[[-1.1332495 , -0.7310898 , -0.0554735 ]],

          [[-0.3009607 , -1.1304651 , -0.76141965]],

          [[ 0.9073713 , -0.51171947,  0.0623714 ]],

          [[-0.40239656,  1.1562593 , -0.8726147 ]],

          [[ 0.03999587, -1.0780708 ,  1.4183995 ]],

          [[ 0.17740378,  0.40933305,  1.1325244 ]]]]]], dtype=float32)

In [ ]:
arr = np.array([1,3,4,2])
tensor = torch.from_numpy(arr)
tensor

tensor([1, 3, 4, 2])

In [ ]:
torch.manual_seed(0)
tensor1 = torch.randn(3,4)
torch.manual_seed(0)
tensor2 = torch.randn(3,4)
print(tensor1 == tensor2)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
# Setting up device agnostic code

device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
tensor = torch.tensor([1,3,4,2,5])
tensor.device

device(type='cpu')

In [ ]:
tensor_gpu = tensor.to(device)
tensor_gpu

tensor([1, 3, 4, 2, 5], device='cuda:0')